# -*- coding: utf-8 -*-
"""Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y5EwT3kFLZyn9OujG6T0K0pw9To4rza
"""

import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="Rekomendasi Mobil Bekas",
    page_icon="🚗",
    layout="wide"
)

# ===========================
# Styling (UI baru, beda dari kopi)
# ===========================
st.markdown("""
<style>
/* Layout */
.block-container { padding-top: 2.2rem; padding-bottom: 2rem; max-width: 1200px; }
h1, h2, h3 { letter-spacing: -0.02em; }

/* Hero */
.hero {
  background: linear-gradient(135deg, rgba(12,18,28,0.92), rgba(33,42,62,0.92));
  padding: 28px 28px;
  border-radius: 20px;
  color: #fff;
  box-shadow: 0 12px 30px rgba(0,0,0,0.22);
  margin-bottom: 18px;
}
.hero-title { font-size: 2.1rem; font-weight: 850; margin: 0; }
.hero-subtitle { font-size: 1rem; opacity: 0.92; margin-top: 8px; margin-bottom: 0; }
.hero-badges { margin-top: 14px; display: flex; gap: 10px; flex-wrap: wrap; }
.badge {
  background: rgba(255,255,255,0.14);
  border: 1px solid rgba(255,255,255,0.18);
  padding: 6px 10px;
  border-radius: 999px;
  font-size: 0.85rem;
  backdrop-filter: blur(6px);
}

/* Cards */
.card {
  background: rgba(255,255,255,0.92);
  border: 1px solid rgba(17,24,39,0.08);
  border-radius: 18px;
  padding: 18px 18px;
  box-shadow: 0 10px 24px rgba(17,24,39,0.06);
  height: 100%;
}
.card h3 { margin-top: 0; }
.muted { color: rgba(17,24,39,0.68); font-size: 0.95rem; }
.kpi {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
  margin-top: 10px;
}
.kpi .pill {
  background: rgba(17,24,39,0.06);
  border: 1px solid rgba(17,24,39,0.08);
  padding: 8px 10px;
  border-radius: 14px;
  font-size: 0.9rem;
}

/* Sidebar look */
section[data-testid="stSidebar"] {
  background: linear-gradient(180deg, #0b1220, #101a2f);
}
section[data-testid="stSidebar"] * { color: #e8eefc !important; }
.small-note { font-size: 0.85rem; opacity: 0.85; }
</style>
""", unsafe_allow_html=True)

# ===========================
# Sidebar (navigasi)
# ===========================
st.sidebar.markdown("## 🚗 Mobil Bekas")
st.sidebar.markdown('<div class="small-note">Website rekomendasi berbasis ML + scoring</div>', unsafe_allow_html=True)
st.sidebar.markdown("---")
st.sidebar.markdown("### Menu")
st.sidebar.write("- Home")
st.sidebar.write("- Rekomendasi Mobil (di halaman pages)")
st.sidebar.write("- Eksplorasi Data (opsional)")


# ===========================
# Main content
# ===========================
st.markdown("""
<div class="hero">
  <p class="hero-title">Rekomendasi Mobil Bekas Sesuai Budget</p>
  <p class="hero-subtitle">
    Masukkan budget & preferensi, lalu sistem akan menyaring dan meranking mobil bekas paling cocok.
    Prediksi harga dilakukan dengan model Machine Learning.
  </p>
  <div class="hero-badges">
    <span class="badge">✅ Filter Budget</span>
    <span class="badge">✅ Prediksi Harga (ML)</span>
    <span class="badge">✅ Ranking Kecocokan</span>
    <span class="badge">✅ Top-N Rekomendasi</span>
  </div>
</div>
""", unsafe_allow_html=True)

col1, col2, col3 = st.columns([1.2, 1, 1])

with col1:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Apa tujuan website ini?")
    st.markdown(
        """
Website ini membantu pengguna memilih **mobil bekas yang cocok** berdasarkan:
- **Budget maksimum**
- **Kebutuhan penumpang**
- Preferensi **transmisi** dan **bahan bakar**
- Kondisi kendaraan (minimal)

Sistem akan:
1) memprediksi harga mobil (ML),
2) menyaring yang masuk budget,
3) memberi **skor kecocokan**,
4) menampilkan **rekomendasi terbaik**.
""".strip()
    )
    st.markdown('<div class="kpi">'
                '<span class="pill">Regresi: Prediksi harga</span>'
                '<span class="pill">Rekomendasi: Ranking</span>'
                '<span class="pill">Output: Top-N</span>'
                '</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Cara pakai (singkat)")
    st.markdown(
        """
1. Buka halaman **Rekomendasi Mobil** di sidebar
2. Isi **budget** dan kebutuhan **penumpang**
3. (Opsional) Atur transmisi/bahan bakar/kondisi
4. Pilih **prioritas** (tahun muda, km rendah, atau harga murah)
5. Lihat **Top rekomendasi** + alasan rekomendasinya
""".strip()
    )
    st.info("Kalau hasil kosong, longgarkan filter atau naikkan budget.")
    st.markdown('</div>', unsafe_allow_html=True)

with col3:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Catatan kualitas hasil")
    st.markdown(
        """
Akurasi rekomendasi sangat dipengaruhi oleh:
- jumlah data mobil di dataset,
- keragaman merk/model,
- kualitas kolom kondisi & kilometer.

Jika dataset masih sedikit, hasil prediksi bisa kurang stabil — ini normal.
""".strip()
    )
    st.markdown("**Saran:** tambah data minimal 100–300 baris untuk hasil lebih bagus.")
    st.markdown('</div>', unsafe_allow_html=True)

st.markdown("---")

# Quick checks (tanpa bikin error kalau file belum ada)
data_ok = Path("data_mobil_bekas.csv").exists()
model_ok = Path("model_mobil_bekas.pkl").exists()

c1, c2, c3 = st.columns(3)
c1.metric("Dataset tersedia", "Ya" if data_ok else "Belum")
c2.metric("Model tersedia", "Ya" if model_ok else "Belum")
c3.metric("Status", "Siap digunakan" if (data_ok and model_ok) else "Perlu file")

st.caption("Next: buat/aktifkan halaman `pages/1_Rekomendasi_Mobil.py` untuk mulai rekomendasi.")