# -*- coding: utf-8 -*-
"""train_model_mobil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwVo4hkvFDKQcE11lDItm6s9D793xY2G
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score


DATA_PATH = "data_mobil_bekas.csv"

# Kolom sesuai dataset baru kamu
FEATURE_COLS = [
    "merk", "model", "segmen", "tahun", "kilometer", "transmisi", "bahan_bakar",
    "kapasitas_cc", "warna", "kota", "jumlah_pemilik", "riwayat_servis",
    "bekas_banjir", "bekas_tabrak", "pajak_hidup", "budget_user_juta"
]

TARGET_PRICE = "harga_jual_juta"
TARGET_SCORE = "rekomendasi_score"


def main():
    df = pd.read_csv(DATA_PATH)

    # Validasi kolom
    required = set(FEATURE_COLS + [TARGET_PRICE, TARGET_SCORE])
    missing = sorted(list(required - set(df.columns)))
    if missing:
        raise ValueError(f"Kolom dataset kurang: {missing}\nKolom yang ada: {list(df.columns)}")

    # Rapikan tipe data numerik
    num_cols = ["tahun", "kilometer", "kapasitas_cc", "jumlah_pemilik", "budget_user_juta", TARGET_PRICE, TARGET_SCORE]
    for c in num_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # Buang baris yang kosong pada kolom penting
    df = df.dropna(subset=FEATURE_COLS + [TARGET_PRICE, TARGET_SCORE]).copy()

    X = df[FEATURE_COLS].copy()
    y_price = df[TARGET_PRICE].copy()
    y_score = df[TARGET_SCORE].copy()

    categorical_cols = [
        "merk", "model", "segmen", "transmisi", "bahan_bakar",
        "warna", "kota", "riwayat_servis", "bekas_banjir", "bekas_tabrak", "pajak_hidup"
    ]
    numeric_cols = ["tahun", "kilometer", "kapasitas_cc", "jumlah_pemilik", "budget_user_juta"]

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
            ("num", "passthrough", numeric_cols),
        ]
    )

    def build_model():
        return Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", RandomForestRegressor(
                n_estimators=400,
                random_state=42
            ))
        ])

    # Split sekali supaya konsisten untuk 2 target
    X_train, X_test, y_price_train, y_price_test, y_score_train, y_score_test = train_test_split(
        X, y_price, y_score, test_size=0.2, random_state=42
    )

    # Model harga
    price_model = build_model()
    price_model.fit(X_train, y_price_train)
    pred_price = price_model.predict(X_test)
    mae_price = mean_absolute_error(y_price_test, pred_price)
    r2_price = r2_score(y_price_test, pred_price)

    # Model score
    score_model = build_model()
    score_model.fit(X_train, y_score_train)
    pred_score = score_model.predict(X_test)
    mae_score = mean_absolute_error(y_score_test, pred_score)
    r2_score_val = r2_score(y_score_test, pred_score)

    print("===== Evaluasi Model Harga (harga_jual_juta) =====")
    print(f"MAE: {mae_price:.2f} juta")
    print(f"R^2:  {r2_price:.3f}")

    print("\n===== Evaluasi Model Kecocokan (rekomendasi_score) =====")
    print(f"MAE: {mae_score:.2f} poin")
    print(f"R^2:  {r2_score_val:.3f}")

    joblib.dump(price_model, "model_harga_mobil.pkl")
    joblib.dump(score_model, "model_score_mobil.pkl")
    print("\nModel disimpan:")
    print("- model_harga_mobil.pkl")
    print("- model_score_mobil.pkl")


if __name__ == "__main__":
    main()