# -*- coding: utf-8 -*-
"""1_Rekomendasi_Mobil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRx7ocGBwowg3r45i94aXIo4KDUmZi7L
"""

import streamlit as st
import pandas as pd
import joblib
import os
from train_model_mobil import main as train_model

st.set_page_config(page_title="Rekomendasi Mobil Bekas", page_icon="🚗", layout="wide")

@st.cache_data
def load_data():
    return pd.read_csv("data_mobil_bekas.csv")

@st.cache_resource
def load_models():
    if not os.path.exists("model_harga_mobil.pkl") or not os.path.exists("model_score_mobil.pkl"):
        st.info("Model belum tersedia. Sedang melatih model, mohon tunggu...")
        train_model()

    price_model = joblib.load("model_harga_mobil.pkl")
    score_model = joblib.load("model_score_mobil.pkl")
    return price_model, score_model

FEATURE_COLS = [
    "merk", "model", "segmen", "tahun", "kilometer", "transmisi", "bahan_bakar",
    "kapasitas_cc", "warna", "kota", "jumlah_pemilik", "riwayat_servis",
    "bekas_banjir", "bekas_tabrak", "pajak_hidup", "budget_user_juta"
]

# rapikan numeric
for c in ["tahun","kilometer","kapasitas_cc","jumlah_pemilik","budget_user_juta","harga_jual_juta","rekomendasi_score"]:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")
df = df.dropna(subset=FEATURE_COLS).copy()

st.title("🚗 Rekomendasi Mobil Bekas")
st.write("Sistem akan memprediksi **harga** dan **skor kecocokan** berdasarkan input budget & preferensi kamu.")

# ===== Sidebar input user =====
st.sidebar.header("Preferensi")

budget = st.sidebar.number_input(
    "Budget (juta rupiah)",
    min_value=10.0,
    max_value=2000.0,
    value=float(df["budget_user_juta"].median()),
    step=5.0
)

top_n = st.sidebar.slider("Jumlah rekomendasi", 3, 20, 8)

merk_opts = ["Semua"] + sorted(df["merk"].dropna().unique().tolist())
segmen_opts = ["Semua"] + sorted(df["segmen"].dropna().unique().tolist())
trans_opts = ["Semua"] + sorted(df["transmisi"].dropna().unique().tolist())
bbm_opts = ["Semua"] + sorted(df["bahan_bakar"].dropna().unique().tolist())
kota_opts = ["Semua"] + sorted(df["kota"].dropna().unique().tolist())

pil_merk = st.sidebar.selectbox("Merk", merk_opts, index=0)
pil_segmen = st.sidebar.selectbox("Segmen", segmen_opts, index=0)
pil_trans = st.sidebar.selectbox("Transmisi", trans_opts, index=0)
pil_bbm = st.sidebar.selectbox("Bahan bakar", bbm_opts, index=0)
pil_kota = st.sidebar.selectbox("Kota", kota_opts, index=0)

min_tahun, max_tahun = int(df["tahun"].min()), int(df["tahun"].max())
tahun_range = st.sidebar.slider("Rentang tahun", min_tahun, max_tahun, (min_tahun, max_tahun), step=1)

km_min, km_max = int(df["kilometer"].min()), int(df["kilometer"].max())
km_range = st.sidebar.slider("Rentang kilometer", km_min, km_max, (km_min, km_max), step=1000)

tanpa_banjir = st.sidebar.checkbox("Hanya yang bukan bekas banjir", value=True)
tanpa_tabrak = st.sidebar.checkbox("Hanya yang bukan bekas tabrak", value=True)
pajak_hidup = st.sidebar.checkbox("Hanya yang pajak hidup", value=False)

# ===== Filter dataset dulu berdasarkan preferensi statis =====
df_f = df.copy()

if pil_merk != "Semua":
    df_f = df_f[df_f["merk"] == pil_merk]
if pil_segmen != "Semua":
    df_f = df_f[df_f["segmen"] == pil_segmen]
if pil_trans != "Semua":
    df_f = df_f[df_f["transmisi"] == pil_trans]
if pil_bbm != "Semua":
    df_f = df_f[df_f["bahan_bakar"] == pil_bbm]
if pil_kota != "Semua":
    df_f = df_f[df_f["kota"] == pil_kota]

df_f = df_f[df_f["tahun"].between(tahun_range[0], tahun_range[1])]
df_f = df_f[df_f["kilometer"].between(km_range[0], km_range[1])]

if tanpa_banjir:
    df_f = df_f[df_f["bekas_banjir"].astype(str).str.lower().isin(["tidak", "no", "false"])]
if tanpa_tabrak:
    df_f = df_f[df_f["bekas_tabrak"].astype(str).str.lower().isin(["tidak", "no", "false"])]
if pajak_hidup:
    df_f = df_f[df_f["pajak_hidup"].astype(str).str.lower().isin(["ya", "yes", "true"])]

st.subheader("Hasil Rekomendasi")
if df_f.empty:
    st.warning("Tidak ada listing yang cocok dengan filter. Coba longgarkan filter.")
    st.stop()

# ===== Prediksi dengan budget user yang baru =====
X_pred = df_f[FEATURE_COLS].copy()
X_pred["budget_user_juta"] = budget  # override budget sesuai input user

df_f = df_f.copy()
df_f["pred_harga_juta"] = price_model.predict(X_pred)
df_f["pred_score"] = score_model.predict(X_pred)

# Filter masuk budget berdasarkan prediksi harga
df_f = df_f[df_f["pred_harga_juta"] <= budget].copy()
if df_f.empty:
    st.warning("Setelah dihitung prediksi harga, tidak ada yang masuk budget. Coba naikkan budget.")
    st.stop()

df_f = df_f.sort_values("pred_score", ascending=False).head(top_n)

def juta(x):  # format juta
    return f"{x:,.1f} jt".replace(",", ".")

tampil = df_f[[
    "id_listing","merk","model","segmen","tahun","kilometer","transmisi","bahan_bakar",
    "kapasitas_cc","warna","kota","jumlah_pemilik","riwayat_servis","bekas_banjir","bekas_tabrak","pajak_hidup"
]].copy()

tampil["Pred Harga"] = df_f["pred_harga_juta"].apply(juta)
tampil["Pred Score"] = df_f["pred_score"].round(1)

tampil["kilometer"] = tampil["kilometer"].astype(int).map(lambda v: f"{v:,} km".replace(",", "."))
tampil["kapasitas_cc"] = tampil["kapasitas_cc"].astype(int)

st.dataframe(tampil.reset_index(drop=True), use_container_width=True)

best = df_f.iloc[0]
st.success(
    f"✅ Rekomendasi terbaik: **{best['merk']} {best['model']} ({int(best['tahun'])})** "
    f"— prediksi harga **{juta(best['pred_harga_juta'])}**, skor **{best['pred_score']:.1f}**"
)

with st.expander("Detail perhitungan"):
    st.write("Budget input (juta):", budget)
    st.write("Top listing berdasarkan prediksi skor, setelah lolos filter & masuk budget.")