# -*- coding: utf-8 -*-
"""2_Eksplorasi_Data_Mobil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN-bwgHx92srP59KeJQvcJI9fR4yz9yU
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Eksplorasi Data Mobil Bekas", page_icon="📊", layout="wide")
px.defaults.template = "plotly_dark"

# ===========================
# UI: Dark dashboard + Cards
# ===========================
st.markdown("""
<style>
.stApp { background: #0f1117; }

.block-container { padding-top: 2rem; padding-bottom: 2rem; max-width: 1400px; }

.card {
  background: rgba(30, 34, 39, 0.92);
  border: 1px solid rgba(255,255,255,0.07);
  border-radius: 18px;
  padding: 18px 18px 8px 18px;
  box-shadow: 0 12px 30px rgba(0,0,0,0.30);
  margin-bottom: 18px;
}

.card-title{
  color: #ffffff;
  font-weight: 800;
  font-size: 1.10rem;
  margin-bottom: 8px;
}

.kpi {
  background: rgba(30, 34, 39, 0.92);
  border: 1px solid rgba(255,255,255,0.07);
  border-radius: 18px;
  padding: 14px 16px;
  box-shadow: 0 12px 30px rgba(0,0,0,0.25);
  margin-bottom: 18px;
}

.small { color: rgba(255,255,255,0.75); font-size: 0.9rem; }

div[data-testid="stPlotlyChart"] > div { margin-top: -8px; }
</style>
""", unsafe_allow_html=True)

def prettify_fig(fig):
    fig.update_layout(
        margin=dict(l=18, r=18, t=20, b=18),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        font=dict(size=12),
    )
    return fig

# ===========================
# Load data
# ===========================
@st.cache_data
def load_data():
    return pd.read_csv("data_mobil_bekas.csv")

df = load_data()

# Pastikan numerik
num_cols = ["tahun","kilometer","kapasitas_cc","jumlah_pemilik","budget_user_juta","harga_jual_juta","rekomendasi_score"]
for c in num_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")

# Drop baris yang penting
df = df.dropna(subset=["merk","model","segmen","tahun","kilometer","transmisi","bahan_bakar","kota","harga_jual_juta","rekomendasi_score"]).copy()

st.title("📊 Eksplorasi Data Mobil Bekas")
st.write("Dashboard ringkas untuk memahami listing mobil: distribusi, harga, kilometer, dan skor rekomendasi.")

# ===========================
# Sidebar Filters
# ===========================
st.sidebar.header("Filter")

def opt_list(col):
    return sorted(df[col].dropna().unique().tolist())

f_merk = st.sidebar.multiselect("Merk", opt_list("merk"), default=opt_list("merk"))
f_segmen = st.sidebar.multiselect("Segmen", opt_list("segmen"), default=opt_list("segmen"))
f_trans = st.sidebar.multiselect("Transmisi", opt_list("transmisi"), default=opt_list("transmisi"))
f_bbm = st.sidebar.multiselect("Bahan bakar", opt_list("bahan_bakar"), default=opt_list("bahan_bakar"))
f_kota = st.sidebar.multiselect("Kota", opt_list("kota"), default=opt_list("kota"))

ymin, ymax = int(df["tahun"].min()), int(df["tahun"].max())
km_min, km_max = int(df["kilometer"].min()), int(df["kilometer"].max())
hmin, hmax = float(df["harga_jual_juta"].min()), float(df["harga_jual_juta"].max())

f_tahun = st.sidebar.slider("Rentang Tahun", ymin, ymax, (ymin, ymax), step=1)
f_km = st.sidebar.slider("Rentang Kilometer", km_min, km_max, (km_min, km_max), step=1000)
f_harga = st.sidebar.slider("Rentang Harga Jual (juta)", float(hmin), float(hmax), (float(hmin), float(hmax)), step=5.0)

only_no_banjir = st.sidebar.checkbox("Hanya bukan bekas banjir", value=False)
only_no_tabrak = st.sidebar.checkbox("Hanya bukan bekas tabrak", value=False)
only_pajak_hidup = st.sidebar.checkbox("Hanya pajak hidup", value=False)

df_f = df[
    df["merk"].isin(f_merk)
    & df["segmen"].isin(f_segmen)
    & df["transmisi"].isin(f_trans)
    & df["bahan_bakar"].isin(f_bbm)
    & df["kota"].isin(f_kota)
    & df["tahun"].between(f_tahun[0], f_tahun[1])
    & df["kilometer"].between(f_km[0], f_km[1])
    & df["harga_jual_juta"].between(f_harga[0], f_harga[1])
].copy()

if only_no_banjir and "bekas_banjir" in df_f.columns:
    df_f = df_f[df_f["bekas_banjir"].astype(str).str.lower().isin(["tidak","no","false"])]

if only_no_tabrak and "bekas_tabrak" in df_f.columns:
    df_f = df_f[df_f["bekas_tabrak"].astype(str).str.lower().isin(["tidak","no","false"])]

if only_pajak_hidup and "pajak_hidup" in df_f.columns:
    df_f = df_f[df_f["pajak_hidup"].astype(str).str.lower().isin(["ya","yes","true"])]

st.sidebar.markdown("---")
st.sidebar.write(f"Baris setelah filter: **{len(df_f)}**")

if df_f.empty:
    st.warning("Data kosong setelah filter. Longgarkan filter di sidebar.")
    st.stop()

# ===========================
# KPI Row
# ===========================
avg_price = df_f["harga_jual_juta"].mean()
median_km = df_f["kilometer"].median()
avg_score = df_f["rekomendasi_score"].mean()

k1, k2, k3, k4 = st.columns(4)
with k1:
    st.markdown('<div class="kpi">', unsafe_allow_html=True)
    st.metric("Jumlah Listing", f"{len(df_f):,}".replace(",", "."))
    st.markdown('</div>', unsafe_allow_html=True)

with k2:
    st.markdown('<div class="kpi">', unsafe_allow_html=True)
    st.metric("Rata-rata Harga", f"{avg_price:,.1f} jt".replace(",", "."))
    st.markdown('</div>', unsafe_allow_html=True)

with k3:
    st.markdown('<div class="kpi">', unsafe_allow_html=True)
    st.metric("Median Kilometer", f"{median_km:,.0f} km".replace(",", "."))
    st.markdown('</div>', unsafe_allow_html=True)

with k4:
    st.markdown('<div class="kpi">', unsafe_allow_html=True)
    st.metric("Rata-rata Skor", f"{avg_score:.1f}")
    st.markdown('</div>', unsafe_allow_html=True)

# ===========================
# DASHBOARD GRID (2x2) - mirip contoh kamu
# ===========================
# 1) Donut segmen
seg = df_f["segmen"].value_counts().reset_index()
seg.columns = ["segmen", "total"]
fig1 = px.pie(seg, names="segmen", values="total", hole=0.55)
fig1.update_traces(textinfo="percent+label")

# 2) Top 5 kota
top_kota = df_f["kota"].value_counts().head(5).reset_index()
top_kota.columns = ["kota", "total"]
fig2 = px.bar(top_kota, x="kota", y="total")
fig2.update_layout(xaxis_title=None, yaxis_title="Total Listing")

# 3) Rata-rata harga per merk (Top 10)
avg_brand = df_f.groupby("merk")["harga_jual_juta"].mean().sort_values(ascending=False).head(10).reset_index()
fig3 = px.bar(avg_brand, x="merk", y="harga_jual_juta")
fig3.update_layout(xaxis_title=None, yaxis_title="Rata-rata Harga (juta)")

# 4) Donut transmisi
tr = df_f["transmisi"].value_counts().reset_index()
tr.columns = ["transmisi", "total"]
fig4 = px.pie(tr, names="transmisi", values="total", hole=0.55)
fig4.update_traces(textinfo="percent+label")

for fg in [fig1, fig2, fig3, fig4]:
    prettify_fig(fg)

c1, c2 = st.columns(2)
with c1:
    st.markdown('<div class="card"><div class="card-title">Distribusi Segmen Mobil</div>', unsafe_allow_html=True)
    st.plotly_chart(fig1, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

with c2:
    st.markdown('<div class="card"><div class="card-title">Top 5 Kota dengan Listing Terbanyak</div>', unsafe_allow_html=True)
    st.plotly_chart(fig2, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

c3, c4 = st.columns(2)
with c3:
    st.markdown('<div class="card"><div class="card-title">Rata-rata Harga per Merk (Top 10)</div>', unsafe_allow_html=True)
    st.plotly_chart(fig3, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

with c4:
    st.markdown('<div class="card"><div class="card-title">Distribusi Transmisi</div>', unsafe_allow_html=True)
    st.plotly_chart(fig4, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

# ===========================
# Tambahan grafik (bagian bawah)
# ===========================
st.markdown("### 📈 Tren & Pola Lainnya")

# Tren harga per tahun
avg_year = df_f.groupby("tahun")["harga_jual_juta"].mean().sort_index().reset_index()
fig5 = px.line(avg_year, x="tahun", y="harga_jual_juta", markers=True)
fig5.update_layout(xaxis_title="Tahun", yaxis_title="Rata-rata Harga (juta)")
prettify_fig(fig5)

# Harga vs kilometer (bin 10k km)
tmp = df_f.copy()
tmp["km_bin"] = (tmp["kilometer"] // 10000) * 10000
avg_km = tmp.groupby("km_bin")["harga_jual_juta"].mean().sort_index().reset_index()
fig6 = px.line(avg_km, x="km_bin", y="harga_jual_juta", markers=True)
fig6.update_layout(xaxis_title="Kilometer (dibinning 10.000)", yaxis_title="Rata-rata Harga (juta)")
prettify_fig(fig6)

cc1, cc2 = st.columns(2)
with cc1:
    st.markdown('<div class="card"><div class="card-title">Rata-rata Harga per Tahun</div>', unsafe_allow_html=True)
    st.plotly_chart(fig5, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

with cc2:
    st.markdown('<div class="card"><div class="card-title">Tren Harga terhadap Kilometer</div>', unsafe_allow_html=True)
    st.plotly_chart(fig6, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

# Tabel data
with st.expander("📄 Lihat data setelah filter"):
    st.dataframe(df_f.reset_index(drop=True), use_container_width=True)

